### ISSUE TITLE
Guice/ErrorInjectingConstructor from unit test

### ISSUE THREAD

**Issue by yerinu2019** [google/flogger#313]
Test code
===
@RunWith(MockitoJUnitRunner.class)
public class MessageSenderTest {
  @Mock @Bind
  MessageService messageService;

  @Inject
  MessageSender sut;

  @Before
  public void setup() {
    Guice.createInjector(BoundFieldModule.of(this)).injectMembers(this);
  }
....

Production code passing test:
======
public class MessageSender {
  private final MessageService messageService;

  @Inject
  public MessageSender(MessageService messageService) {
    this.messageService = messageService;
  }

  public boolean sendMessage(String msg, String recipient) {
    return messageService.sendMessage(msg, recipient);
  }
}

Production code failing test with a static FluentLogger:
====
public class MessageSender {
  private static final FluentLogger logger = FluentLogger.forEnclosingClass();

  private final MessageService messageService;

  @Inject
  public MessageSender(MessageService messageService) {
    this.messageService = messageService;
  }

  public boolean sendMessage(String msg, String recipient) {
    return messageService.sendMessage(msg, recipient);
  }
}
...
Error message:
===
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: ExceptionInInitializerError
  at MessageSender.<init>(MessageSender.java:12)
  at MessageSenderTest.sut(MessageSenderTest.java:18)
      \_ for field sut
  while locating MessageSenderTest

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

**Comment by netdpb** [comment]
I don't see anything in that error that appears to have anything to do with Flogger. Can you post the full stack trace?

**Comment by yerinu2019** [comment]
This is all error stack trace that shows up when unit test fails.

at MessageSender.(MessageSender.java:12)
at MessageSenderTest.sut(MessageSenderTest.java:18)
_ for field sut
while locating MessageSenderTest

The error does not occur if I delete this one line from the source code.

private static final FluentLogger logger = FluentLogger.forEnclosingClass();

**Comment by yerinu2019** [comment]
Missed the top line of the error message.

com.google.inject.ProvisionException: Unable to provision, see the following errors:
at MessageSender.(MessageSender.java:12)
at MessageSenderTest.sut(MessageSenderTest.java:18)
_ for field sut
while locating MessageSenderTest

**Comment by yerinu2019** [comment]
Is there any FluentLogger guice module that I have to install in the unit test?

**Comment by netdpb** [comment]
No there isn't.

This looks like either a Guice bug or a problem with your classpath, such that the reflection that Guice is doing on the class is confused by the reference to `FluentLogger`. There is a `ProvisionError` but it looks like there are no messages about it.

I was not able to reproduce the error. If you have more details about your build configuration, maybe that would help.

**Comment by yerinu2019** [comment]
Here is more stack trace...

at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:74)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:1062)
	at org.example.message.MessageNotifierTest.setup(MessageNotifierTest.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.ExceptionInInitializerError
	at com.google.common.flogger.backend.Platform.getCallerFinder(Platform.java:189)
	at com.google.common.flogger.FluentLogger.forEnclosingClass(FluentLogger.java:70)
	at org.example.message.MessageNotifier.<clinit>(MessageNotifier.java:9)
	at org.example.message.MessageNotifier$$FastClassByGuice$$2218237.GUICE$TRAMPOLINE(<generated>)
	at org.example.message.MessageNotifier$$FastClassByGuice$$2218237.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:72)
	... 33 more
Caused by: java.lang.IllegalStateException: No logging platforms found:
com.google.common.flogger.backend.system.DefaultPlatform: java.lang.ClassNotFoundException: com.google.common.flogger.backend.system.DefaultPlatform
	at com.google.common.flogger.backend.Platform$LazyHolder.loadFirstAvailablePlatform(Platform.java:98)
	at com.google.common.flogger.backend.Platform$LazyHolder.<clinit>(Platform.java:66)
	... 46 more

**Comment by yerinu2019** [comment]
My bad.
I didn't add flogger-system-backend to maven dependency.
